version: "3"

services: 

    web-mvc:
        image: geekstore-web-mvc-ecommerce:latest
        container_name: geekstore-web-mvc-ecommerce
        build:
            context: ../src
            dockerfile: ./Web/GeekStore.WebApp.MVC/Dockerfile
        ports:
             - "5001:5001"
        environment:
            - ASPNETCORE_ENVIRONMENT=Production
            - ASPNETCORE_URLS=http://*:5001
     
